[package]
name = "apvrp"
version = "0.1.0"
authors = ["yanni_rist <yanni555rist@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
grb = "1.0.2"
itertools = "0.10.0"
instances = {path = "../instances"}
fnv = "1.0.7"

[[bin]]
name = "apvrp"
path = "src/bin/main.rs"