[package]
name = "apvrp"
version = "0.1.0"
authors = ["yanni_rist <yanni555rist@gmail.com>"]
edition = "2018"
default-run="apvrp"

[dependencies]
anyhow = "1.0.38"
#grb = "^1.0.3"
#grb = { git = "https://github.com/ykrist/rust-grb", branch="dogfood" }
grb = { path = "./grb"}
itertools = "0.10.0"
instances = {path = "../instances"}
fnv = "1.0.7"
serde = { version= "^1.0.123", features = ["derive"] }
serde_json = "^1.0.64"
tracing =  {version = "0.1",  features = ["max_level_trace", "release_max_level_off"]}
tracing-subscriber = { version = "0.2", features = ["json"] }
tracing-appender = "0.1"
variant_count = "^1.1.0"
prettytable-rs = "^0.8"
slurm-harray = { git = "ssh://git@bitbucket.org/yannik_rist/slurm-utils-rs.git" }
smallvec = "^1.6.1"
regex = "^1.5.4"
clap = "^2.33.3"
lazy_static = "1.4.0"
dot = "0.1.4"
daggylp = { path = "./daggylp" }

[[bin]]
name = "apvrp"
path = "src/bin/main.rs"
